### ISSUE TITLE
Not working on iPad portrait.

### ISSUE THREAD

**Issue by jacobmohl** [evgenyneu/ios-imagescroll-swift#3] opened 2015-05-28 19:21 UTC
It seems to work on iPad when its horisontal, but not i portrait mode :-(

**Comment by evgenyneu** [comment] 2015-05-28 21:01
Hi, thanks for reporting. Is it this demo app that is not working? Or is
not working in your app?

**Comment by jacobmohl** [comment] 2015-06-09 19:31
The demo app dont work when you simulate it with a iPad.

The images is not centered correctly, and you can't zoom out so you can see the whole image.

**Comment by evgenyneu** [comment] 2015-06-09 21:22
@jacobmohl thanks for clarification. I could not reproduce it on iPad simulator unfortunately. I launched it in landscape and did the zoom in / zoom out. It would be great if you could write the exact steps for reproducing the problem. Thanks.

 Xcode: 6.3.2 (6D2105)

**Comment by evgenyneu** [comment] 2015-08-31 11:54
Closing the issue, feel free to open it again if you need.

**Closed as completed by evgenyneu** 2015-08-31 11:54 UTC
